name: "Information Commons Standard PR Checks"
description: "Checks .info.md files against starter test kit for reviewers."
inputs:
  prompt:
    description: "Manual override of prompt."
outputs:
  messages:
    description: "Message for modified info file."
  testOp:
    description: "yolo"
runs:
  using: "node12"
  main: "dist/index.js"
